name: Android Signing

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: flutter-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_CHANNEL: stable
  JAVA_VERSION: '17'

jobs:
  android_web:
    name: Android
    runs-on: macos-26
    environment: ANDROID_KEYSTORE_BASE64   # <-- so wird das Environment aktiviert
    
    steps:
      - uses: actions/checkout@v4

      # - name: Set up Java
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: zulu
      #     java-version: ${{ env.JAVA_VERSION }}

      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: ${{ env.FLUTTER_CHANNEL }}
      #     cache: true

      # - name: Install dependencies
      #   run: flutter pub get
        

    steps:
      - uses: actions/checkout@v4
      ...
      - name: Decode keystore
        run: |
          mkdir -p android/app
          printf "%s" "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -D > android/app/release.jks
          ls -lh android/app/release.jks
